decode: decode.py
	python3 decode.py decode $(ARGS)

encode: encode.py
	python3 encode.py encode $(ARGS)

# crack: crack.py
# 	python3 decode.py decode $(ARGS)

# guesskeylength: guesskeylength.py
# 	python3 decode.py decode $(ARGS)