decode: decode.py
	python3 decode.py $(ARGS)

encode: encode.py
	python3 encode.py $(ARGS)

crack: Crack.py
	python3 Crack.py $(ARGS)

guesskeylength: guesskeylength.py
	python3 guesskeylength.py $(ARGS)